config/routes.rb
Rails.application.routes.draw do
  get 'logs/index'
  devise_for :users
  get '/input', to: 'data#input'
  post '/generate', to: 'data#generate'
  post '/generate_guardian', to: 'pages#generate_guardian'
  get 'download_staff_csv', to: 'data#download_staff_csv'
  get 'download_students_csv', to: 'data#download_students_csv'
  get 'download_classes_csv', to: 'data#download_classes_csv'
  get 'download_enrollment_csv', to: 'data#download_enrollment_csv'
  get 'download_guardian_csv', to: 'pages#download_guardian_csv'
  root 'data#input'
  get 'data/guardian'
  get 'data/guardian', to: 'data#guardian'
  resources :logs, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/data_controller.rb
require_relative '../services/data_generator'

class DataController < ApplicationController
  include DataGenerator

  def input
  end

  def generate
    num_staff = params[:num_staff].to_i
    num_students = params[:num_students].to_i
    num_classes = params[:num_classes].to_i
    num_buildings = params[:num_buildings].to_i
    num_students_per_class = params[:num_students_per_class].to_i
    num_staff_per_class = params[:num_staff_per_class].to_i
    student_email = params[:student_email]
    staff_email = params[:staff_email]

    DataGenerator.generate_staff_data(num_staff, staff_email)
    DataGenerator.generate_student_data(num_students, student_email)
    DataGenerator.generate_classes_data(num_classes, num_buildings)
    DataGenerator.generate_enrollment_data(num_classes, num_students_per_class, num_staff_per_class, num_staff, num_students)

    redirect_to root_path, notice: 'Data generated successfully!'
    session[:data_generation_complete] = true
  end

  def download_staff_csv
    send_file "#{Rails.root}/artifact/staff.csv"
  end

  def download_students_csv
    send_file "#{Rails.root}/artifact/students.csv"
  end

  def download_classes_csv
    send_file "#{Rails.root}/artifact/classes.csv"
  end

  def download_enrollment_csv
    send_file "#{Rails.root}/artifact/enrollment.csv"
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @logs = File.readlines(Rails.root.join('log', 'development.log'))
  end
end

app/controllers/pages_controller.rb
require_relative '../services/data_generator'

class PagesController < ApplicationController
  include DataGenerator

  def guardian
  end

def generate_guardian
  num_guardian = params[:num_guardian].to_i
  num_student_id = params[:num_student_id].to_i
  guardian_email = params[:guardian_email]

  DataGenerator.generate_guardian_data(num_guardian, num_student_id, guardian_email)

  redirect_to root_path, notice: 'Data generated successfully!'
  session[:data_generation_complete] = true
end

def download_guardian_csv
  send_file "#{Rails.root}/artifact/guardian.csv"
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/data/guardian.html.erb
<html>
<head>
  <title>DataGenerationApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application' , media: 'all' , 'data-turbolinks-track' => 'reload' %>
        <%# <%= javascript_pack_tag 'application' , 'data-turbolinks-track' => 'reload' %>
          <style>
            .container {
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
              background-color: #f9f9f9;
              border-radius: 8px;
            }

            h1 {
              font-size: 2em;
              text-align: center;
              margin-bottom: 20px;
            }

            form {
              margin-bottom: 20px;
            }

            table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 20px;
            }

            table td {
              padding: 20px;
              border: 1px solid #ccc;
            }

            label {
              font-weight: bold;
            }

            input[type="number"] {
              width: 100%;
              padding: 8px;
              border: 1px solid #ccc;
              border-radius: 4px;
            }

            .btn-primary {
              background-color: #007bff;
              color: #fff;
              padding: 10px 20px;
              border: none;
              border-radius: 4px;
              cursor: pointer;
              font-size: 16px;
            }

            .btn-primary:hover {
              background-color: #0056b3;
            }

            #loadingMessage {
              display: none;
              text-align: center;
              font-size: 1.2em;
            }
          </style>
</head>
<body>
  <h1 class="mb-4">Guardian List Generation Form</h1>
  <%= form_with(url: generate_guardian_path, method: :post, class: 'mb-4' , id: "dataForm" ) do |form| %>
    <table style="height: 1px">
      <tbody>
        <tr>
          <td class="align-bottom">
            <%= form.label :guardian_email, 'Guardian Source Email' %>
            <p class="description">Emails will be generated using this email</p>
          </td>
          <td class="align-bottom">
            <input type="email" id="guardian_email" name="guardian_email" required maxlength="100" class="form-control" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" placeholder="example@example.com">
          </td>
        <tr>
          <td class="align-bottom">
            <%= form.label :num_guardian, 'Number of Guardian' %>
          </td>
          <td class="align-bottom">
            <%= form.number_field :num_guardian, min: 1, max: 99999, required: true, class: 'form-control' ,
              oninput: 'limitInputLength(this, 5)', placeholder: 'max 99999'   %>
          </td>
        </tr>
        <tr>
         
          <td class="align-bottom">
            <%= form.label :num_student_id, 'Student ID' %>
            <p class="description">Existing Student ID</p>
          </td>
          <td class="align-bottom">
            <%= form.number_field :num_student_id, min: 1, max: 99999999999999999999, required: true, class: 'form-control' ,
              oninput: 'limitInputLength(this, 20)', placeholder: 'Student ID'   %>
          </td>
       
      </tbody>
    </table>
    <div class="text-center mt-4">
      <%= form.submit 'Generate Data' , class: 'btn btn-primary', id: 'generateButton' %>
    </div>
    <% end %>
      </div>
      <div id="loadingMessage" style="display: none; color: red;">
        Generating Term Files, please don't refresh page. It may take a few minutes for a large enrollment.
      </div>
</body>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</html>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var form = document.getElementById("dataForm");
    var loadingMessage = document.getElementById("loadingMessage");

    form.addEventListener("submit", function (event) {
      event.preventDefault();

      var numGuardians = parseInt(document.getElementById("num_guardian").value);
      var numStudentIds = parseInt(
        document.getElementById("num_student_id").value
      );
      
      generateButton.disabled = true;
      loadingMessage.style.display = "block";

      var formData = new FormData(form);

      var xhr = new XMLHttpRequest();
      xhr.open("POST", form.action, true);
      xhr.onload = function () {
        if (xhr.status === 200) {
          setTimeout(function () {
            window.location.href = "<%= download_guardian_csv_path %>";
          }, 1000);

          generateButton.disabled = false;
          loadingMessage.style.display = "none";
        }
      };
      xhr.send(formData);
    });
  });
</script>
<script>
  function limitInputLength(input, maxLength) {
    if (input.value.length > maxLength) {
      input.value = input.value.slice(0, maxLength);
    }
  }
</script>

app/views/data/input.html.erb
<html>
<head>
  <title>DataGenerationApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application' , media: 'all' , 'data-turbolinks-track' => 'reload' %>
        <%# <%= javascript_pack_tag 'application' , 'data-turbolinks-track' => 'reload' %>
          <style>
            .container {
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
              background-color: #f9f9f9;
              border-radius: 8px;
            }

            h1 {
              font-size: 2em;
              text-align: center;
              margin-bottom: 20px;
            }

            form {
              margin-bottom: 20px;
            }

            table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 20px;
            }

            table td {
              padding: 20px;
              border: 1px solid #ccc;
            }

            label {
              font-weight: bold;
            }

            input[type="number"] {
              width: 117%;
              padding: 8px;
              border: 1px solid #ccc;
              border-radius: 4px;
            }

            .btn-primary {
              background-color: #007bff;
              color: #fff;
              padding: 10px 20px;
              border: none;
              border-radius: 4px;
              cursor: pointer;
              font-size: 16px;
            }

            .btn-primary:hover {
              background-color: #0056b3;
            }

            #loadingMessage {
              display: none;
              text-align: center;
              font-size: 1.2em;
            }
          </style>
</head>
<body>
  <h1 class="mb-4">Term List Generation Form</h1>
  <%= form_with(url: generate_path, method: :post, class: 'mb-4' , id: "dataForm" ) do |form| %>
    <table style="height: 1px">
      <tbody>
        <tr>
          <td class="align-bottom">
            <%= form.label :num_staff, 'Number of Staff' %>
          </td>
          <td class="align-bottom">
            <%= form.number_field :num_staff, min: 1, max: 99999, required: true, class: 'form-control' ,
              oninput: 'limitInputLength(this, 5)', placeholder: 'max 99999'   %>
          </td>
          <td class="align-bottom">
            <%= form.label :staff_email, 'Staff Source Email' %>
            <p class="description">Emails will be generated using this email</p>
          </td>
          <td class="align-bottom">
            <input type="email" id="staff_email" name="staff_email" required maxlength="100" class="form-control" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" placeholder="example@example.com">
          </td>
        </tr>
        <tr>
          <td class="align-bottom">
            <%= form.label :num_students, 'Number of Students' %>
          </td>
          <td class="align-baseline">
            <%= form.number_field :num_students, min: 1, max: 99999, required: true, class: 'form-control' ,
              oninput: 'limitInputLength(this, 5)', placeholder: 'max 99999'   %>
          </td>
          <td class="align-bottom">
            <%= form.label :student_email, 'Student Source Email' %>
            <p class="description">Emails will be generated using this email</p>
          </td>
          <td class="align-bottom">
            <input type="email" id="student_email" name="student_email" required maxlength="100" class="form-control" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" placeholder="example@example.com">
          </td>
        </tr>
        <tr>
          <td class="align-bottom">
            <%= form.label :num_classes, 'Number of Classes' %>
          </td>
          <td class="align-baseline">
            <%= form.number_field :num_classes, min: 1, max: 999, required: true, class: 'form-control' ,
              oninput: 'limitInputLength(this, 3)', placeholder: 'max 999'   %>
          </td>
        </tr>
        <tr>
          <td class="align-bottom">
            <%= form.label :num_buildings, 'Number of Buildings' %>
          </td>
          <td class="align-baseline">
            <%= form.number_field :num_buildings, min: 1, max: 999, required: true, class: 'form-control' ,
              oninput: 'limitInputLength(this, 3)', placeholder: 'max 999'  %>
          </td>
        </tr>
        <tr>
          <td class="align-bottom">
            <%= form.label :num_students_per_class, 'Number of Students per Class' %>
          </td>
          <td class="align-baseline">
            <%= form.number_field :num_students_per_class, min: 0, max: 9999, required: true, class: 'form-control' ,
              oninput: 'limitInputLength(this, 4)', placeholder: 'max 9999'   %>
          </td>
        </tr>
        <tr>
          <td class="align-bottom">
            <%= form.label :num_staff_per_class, 'Number of Staff per Class' %>
          </td>
          <td class="align-baseline">
            <%= form.number_field :num_staff_per_class, min: 0, max: 9999, required: true, class: 'form-control' ,
              oninput: 'limitInputLength(this, 4)', placeholder: 'max 9999'   %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="text-center mt-4">
      <%= form.submit 'Generate Data' , class: 'btn btn-primary', id: 'generateButton' %>
    </div>
    <% end %>
      </div>
      <div id="loadingMessage" style="display: none; color: red;">
        Generating Term Files, please don't refresh page. It may take a few minutes for a large enrollment.
      </div>
</body>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</html>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var form = document.getElementById("dataForm");
    var loadingMessage = document.getElementById("loadingMessage");

    form.addEventListener("submit", function (event) {
      event.preventDefault();


      var numStudents = parseInt(document.getElementById("num_students").value);
      var numStudentsPerClass = parseInt(
        document.getElementById("num_students_per_class").value
      );

      if (numStudentsPerClass > numStudents) {
        alert(
          "Number of students per class cannot be more than total number of students."
        );
        return;
      }

      var numStaff = parseInt(document.getElementById("num_staff").value);
      var numStaffPerClass = parseInt(
        document.getElementById("num_staff_per_class").value
      );

      if (numStaffPerClass > numStaff) {
        alert(
          "Number of staff per class cannot be more than total number of staff."
        );
        return;
      }
      
      generateButton.disabled = true;
      loadingMessage.style.display = "block";

      var formData = new FormData(form);

      var xhr = new XMLHttpRequest();
      xhr.open("POST", form.action, true);
      xhr.onload = function () {
        if (xhr.status === 200) {
          setTimeout(function () {
            window.location.href = "<%= download_staff_csv_url %>";
          }, 1000);

          setTimeout(function () {
            window.location.href = "<%= download_students_csv_url %>";
          }, 2000);

          setTimeout(function () {
            window.location.href = "<%= download_classes_csv_url %>";
          }, 3000);

          setTimeout(function () {
            window.location.href = "<%= download_enrollment_csv_url %>";
          }, 4000);

          generateButton.disabled = false;
          loadingMessage.style.display = "none";
        }
      };
      xhr.send(formData);
    });
  });
</script>
<script>
  function limitInputLength(input, maxLength) {
    if (input.value.length > maxLength) {
      input.value = input.value.slice(0, maxLength);
    }
  }
</script>

app/views/layouts/_header.html.erb
<% if current_user %>
<span style="color: white;"><%= current_user.email %></span>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataGenerationApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Term List Generation', root_path, class: 'navbar-brand' %>
  <%= link_to 'Guardian List Generation', data_guardian_path, class: 'navbar-brand' %>
  <div class="ml-auto">
      <%= render 'layouts/header' %>
  </div>
  </nav>
<div class="container">
  <p class="notice" style="text-align: center; color: blue;"><%= notice %></p>
  <p class="alert" style="text-align: center; color: blue;"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/logs/index.html.erb
<h1>Logs</h1>
<ul>
  <% @logs.each do |log| %>
    <li><%= log %></li>
  <% end %>
</ul>

app/views/pages/guardian.html.erb
<h1>Pages#guardian</h1>
<p>Find me in app/views/pages/guardian.html.erb</p>